export const position = [68.524, 105.3188];

export const allStationNames = [
  "arti",
  "artu",
  "bilb",
  "bili",
  "irkm",
  "irkt",
  "lovj",
  "mag0",
  "magj",
  "mobj",
  "mobk",
  "mobn",
  "nril",
  "petp",
  "petr",
  "pets",
  "tixi",
  "tixj",
  "yaka",
  "yakt",
  "yakz",
  "yssk",
];

export const activeStations = [
  { Name: "arti", Latitude: "56.430", Longitude: "58.560" },
  { Name: "artu" },
  { Name: "irkm" },
  { Name: "irkt", Latitude: "52.219", Longitude: "104.316" },
  { Name: "mag0" },
  { Name: "mobj" },
  { Name: "mobk" },
  { Name: "mobn" },
  { Name: "nril" },
  { Name: "pets" },
  { Name: "tixi" },
  { Name: "tixj", Latitude: "71.634", Longitude: "128.866" },
  { Name: "yakt" },
  { Name: "yssk" },
];
